### ISSUE TITLE
Bundled distribution of liboping should run autogen before packaging/upload.

### ISSUE THREAD

**Issue by Roughsketch** [cfallin/rust-oping#8]
I've been trying to use this crate but I haven't been able to get it to compile. Here is my exact error:

```
error: failed to run custom build command for `oping v0.3.3`
process didn't exit successfully: `/home/fish/Documents/GitHub/uptime/target/debug/build/oping-b54eda40329bedc1/build-script-build` (exit code: 101)
--- stderr
autogen.sh: 5: autogen.sh: autoreconf: not found
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', /checkout/src/libcore/result.rs:906:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

With backtrace enabled it's pointing to line 11 of build.rs, which makes me think the `./configure` command is causing the error. Here's an excerpt from the backtrace:

```
  11: build_script_build::main
             at ./build.rs:11
```

Am I doing something wrong or is this a bug?

**Comment by cfallin** [comment]
If you look closely at the error message, this is the key line:

    autogen.sh: 5: autogen.sh: autoreconf: not found

The underlying `liboping` C library, which this crate bundles and builds privately, requires `autoconf` and `automake` to build because we just bundle its Git repo as a submodule. I suppose we could run `autogen.sh` locally before packaging and uploading, though -- would involve vendoring the code into our repo and checking those artifacts into Git. I'll see if I can get to it in a bit (I'm quite busy with other stuff at the moment, sorry!).

Thanks for the report!

**Comment by cfallin** [comment]
(But, for now, for clarity -- the solution is simply to install autoconf/automake. On Linux these should be easy-to-find packages, e.g. `apt install autoconf` and `apt install automake` on Ubuntu.)

**Comment by Roughsketch** [comment]
After installing those as well as `libtool` I got it to compile. Thanks.

**Comment by kacejot** [comment]
Hi, guys.
I still have the problem with build after installing all the dependencies:
```
error: failed to run custom build command for `oping v0.3.3`

Caused by:
  process didn't exit successfully: `./target/debug/build/oping-d703d4337edefa2a/build-script-build` (exit code: 101)
--- stdout
autoconfiguration done, to build: ./configure ; make
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = None
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
DEBUG = Some("true")
running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-I" "liboping/src/" "-DHAVE_CONFIG_H" "-Wall" "-Wextra" "-o" "./target/debug/build/oping-4410bab83b8a954e/out/liboping/src/liboping.o" "-c" "liboping/src/liboping.c"
cargo:warning=liboping/src/liboping.c:25:11: fatal error: config.h: No such file or directory
cargo:warning= # include <config.h>
cargo:warning=           ^~~~~~~~~~
cargo:warning=compilation terminated.
exit code: 1

--- stderr
aclocal: warning: couldn't open directory 'm4': No such file or directory
configure.ac:57: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:57: You should run autoupdate.
../../lib/autoconf/general.m4:207: AC_HELP_STRING is expanded from...
configure.ac:57: the top level
configure.ac:57: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:57: You should run autoupdate.
../../lib/autoconf/general.m4:207: AC_HELP_STRING is expanded from...
configure.ac:57: the top level
configure.ac:50: installing './config.guess'
configure.ac:50: installing './config.sub'
configure: error: in `~/.cargo/registry/src/github.com-1ecc6299db9ec823/oping-0.3.3/liboping':
configure: error: cannot compute suffix of executables: cannot compile and link
See `config.log' for more details
thread 'main' panicked at '

Internal error occurred: Command "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-I" "liboping/src/" "-DHAVE_CONFIG_H" "-Wall" "-Wextra" "-o" "./target/debug/build/oping-4410bab83b8a954e/out/liboping/src/liboping.o" "-c" "liboping/src/liboping.c" with args "cc" did not execute successfully (status code exit code: 1).

', ~/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.55/src/lib.rs:1672:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by cfallin** [comment]
Can you check whether you're able to build `liboping` (not this wrapper crate, but the original C library) on your system?

The issue seems to be that './configure' for the C library doesn't actually execute correctly:

```
configure: error: cannot compute suffix of executables: cannot compile and link
See `config.log' for more details
```

(I'm starting to think that bundling the C library into the crate was a bad idea, given that all the support issues have to do with getting it to build, but that's neither here nor there...)

**Comment by nhed** [comment]
*Edit*: this will modify a file in  submodule and hence not ideal for submission, just a local workaround.

---------------------------

Very much a rust newb, had similar problems, solved with adding autoupdate to `build.rs`
```
 fn main() {
+    Command::new("autoupdate")
+        .current_dir("liboping/")
+        .status()
+        .unwrap();
     Command::new("sh")
         .current_dir("liboping/")
         .arg("autogen.sh")
```

and yeah trying to build the tip of `liboping`, I'm told to autoupdate
```
$ ./autogen.sh 
configure.ac:57: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:57: You should run autoupdate.
../../lib/autoconf/general.m4:207: AC_HELP_STRING is expanded from...
configure.ac:57: the top level
configure.ac:57: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:57: You should run autoupdate.
```

**Comment by cfallin** [comment]
Just pushed version 0.4.0, which removes the bundled `liboping` and requires it to be installed on the system, due to continued support burden of build issues. (Sorry! I don't have infinite free time, unfortunately...). Closing this issue as it's no longer applicable.
